name:                IAManager
version:             0.1.0.0
github:              "certainty/IAManager"
license:             BSD3
author:              "certainty"
maintainer:          "david.krentzlin@gmail.com"
copyright:           "I don&#39;t care"

extra-source-files:
- README.md
- ChangeLog.md

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

default-extensions:
  - NoImplicitPrelude
  - ConstraintKinds
  - DeriveGeneric
  - DerivingStrategies
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - OverloadedStrings
  - RecordWildCards
  - NamedFieldPuns
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - ViewPatterns
  - ApplicativeDo
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/certainty/IAManager#readme>


dependencies:
  - base >= 4.7 && < 5
  - relude
  - safe-exceptions
  - bytestring
  - text

library:
  source-dirs: src

executables:
  iaManage:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    ld-options:
    - -pthread
    dependencies:
    - IAManager
    - optparse-applicative
    - directory
    - filepath

benchmarks:
  IAManager-benchmark:
    main: Main.hs
    source-dirs: benchmark
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - IAManager
    - gauge

tests:
  IAManeger-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hedgehog
    - tasty
    - tasty-hedgehog
    - tasty-discover
    - tasty-hspec
    - IAManager
    - raw-strings-qq
    - vector
